version: '3.3'
services:
  db:
    image: mongo:${MONGO_IMAGE_VERSION}
    volumes:
      - post_db:/data/db
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      reddit_back:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USER_NAME}/ui:${UI_IMAGE_VERSION}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - reddit_front
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
  post:
    image: ${USER_NAME}/post:${POST_IMAGE_VERSION}
    networks:
      - reddit_back
      - reddit_front
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
  comment:
    image: ${USER_NAME}/comment:${COMMENT_IMAGE_VERSION}
    networks:
      - reddit_back
      - reddit_front
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

volumes:
  post_db:

networks:
  reddit_front:
  reddit_back:
