version: '3.3'
services:
  db:
    image: mongo:${MONGO_IMAGE_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      reddit_back:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:${UI_IMAGE_VERSION}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - reddit_front
    volumes:
      - ./ui:/app
    command: ["puma", "--debug", "-w", "2"]
  post:
    image: ${USERNAME}/post:${POST_IMAGE_VERSION}
    networks:
      - reddit_back
      - reddit_front
    volumes:
      - ./post-py:/app
  comment:
    image: ${USERNAME}/comment:${COMMENT_IMAGE_VERSION}
    networks:
      - reddit_back
      - reddit_front
    volumes:
      - ./comment:/app
    command: ["puma", "--debug", "-w", "2"]

volumes:
  post_db:

networks:
  reddit_front:
  reddit_back:
